[workspace]
authors = ["stijn", "benny", "andres"]
channels = ["conda-forge", "https://conda.modular.com/max"]
description = "Basalt is a stand-alone machine learning framework that leverages the power of Mojo."
name = "Basalt"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
test = { cmd = "magic run mojo test -I . tests" }
test_mojo = { cmd = "magic run mojo test -I . tests/mojo" }
test_python = { cmd = "magic run mojo test -I . tests/python" }

[dependencies]
max = ">=26.3.0,<27"
pytorch = ">=2.11.0,<3"
torchvision = ">=0.26.0,<0.27"
torchaudio = ">=2.11.0,<3"
onnx = ">=1.21.0,<2"
pandas = ">=3.0.3,<4"
modular = ">=26.3.0,<27"  
#mojo -I . examples/housing.mojo max = ">=24.6.0"

[pypi-dependencies]
# torch = ">=2.5.1, <3"
# torchvision = ">=0.20.1, <0.21"
# torchaudio = ">=2.5.1, <3"
# onnx = ">=1.17.0, <2"
