[workspace]
authors = ["shivasankar"]
channels = ["conda-forge", "https://conda.modular.com/max", "https://conda.modular.com/max-nightly"]
description = "Mantle is a stand-alone machine learning framework that leverages the power of Mojo."
license = "Apache-2.0 WITH LLVM-exception"
name = "Mantle"
platforms = ["osx-arm64", "linux-64"]
preview = ["pixi-build"]
readme = "README.md"
version = "0.1.0"

[package]
name = "mantle"
version = "0.1.0"

[package.build]
backend = { name = "pixi-build-mojo", version = "0.*", channels = [
  "https://prefix.dev/pixi-build-backends",
  "https://prefix.dev/conda-forge",
] }

[package.build.config.pkg]
name = "mantle"

[package.host-dependencies]
mojo = "==1.1.0"
max-core = "==26.6.0"

[package.build-dependencies]
mojo = "==1.1.0"
max-core = "==26.6.0"

[package.run-dependencies]
mojo = "==1.1.0"
max-core = "==26.6.0"

[tasks]
test_mojo = { cmd = "mojo test -I . tests/mojo" }
format = { cmd = "mojo format mantle/" }
precompile = { cmd = "mojo precompile mantle -o mantle.mojoc" }
doc_pages = { cmd = "mojo doc mantle -o docs.json" }

[dependencies]
mojo = ">=1.1.0,<2"
max-core = ">=26.6.0,<27"

[feature.torch.dependencies]
pytorch = ">=2.12.1,<3"
numpy = ">=2,<3"

[feature.python-examples.dependencies]
pandas = ">=3.0.3,<4"
matplotlib = ">=3.11.0,<4"

[feature.onnx.dependencies]
onnx = ">=1.22.0,<2"

[feature.visualization.dependencies]
netron = ">=9.1.3,<10"

[feature.test.tasks]
test = { cmd = "mojo test -I . tests" }
test_python = { cmd = "mojo test -I . tests/python" }

[environments]
test = ["torch", "onnx", "test"]
examples = ["torch", "python-examples", "onnx"]
visualize = ["onnx", "visualization"]
