[workspace]
authors = ["stijn", "benny", "andres"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge", "https://conda.modular.com/max"]
description = "Mantle is a stand-alone machine learning framework that leverages the power of Mojo."
name = "Mantle"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]
test = { cmd = "mojo test -I . tests" }
test_mojo = { cmd = "mojo test -I . tests/mojo" }
test_python = { cmd = "mojo test -I . tests/python" }
format = { cmd = "mojo format mantle/" }
precompile = { cmd = "mojo precompile mantle -o mantle.mojoc" }

[dependencies]
pytorch = ">=2.11.0,<3"
torchvision = ">=0.26.0,<0.27"
torchaudio = ">=2.11.0,<3"
onnx = ">=1.21.0,<2"
pandas = ">=3.0.3,<4"
mojo = ">=1.0.0b3.dev2026061606,<2"
matplotlib = ">=3.11.0,<4"
netron = ">=9.1.1,<10"

[pypi-dependencies]
# torch = ">=2.5.1, <3"
# torchvision = ">=0.20.1, <0.21"
# torchaudio = ">=2.5.1, <3"
# onnx = ">=1.17.0, <2"
